#!/bin/bash

#This script is used to make a copy of 17_03
#$1=pathname (/usr/neha)
#$2=old directory name ( 17_03)
#$3=new directory name (17_04)
#$4=The other directory which you want to copy (Hieradata)

echo "started printing"
#cp -rvf $1/$2 $1/$3

#Copying the folder from 17_03 to 17_04
cp -rvf $1/$2 $1/$3

#Copying the folder from Hieradata/17_03 to Hieradata/17_04
cp -rvf $1/$4/$2 $1/$4/$3

#Searching for the 17_03 files in the 17_04 directory and storing the value in a
a=`grep -lr $2 $1/$3 $1/$4/$3`

#Replacing 17_03 with 17_04 
for b in $a
do
 echo $b; 
 sed -i s/$2/$3/g $b
done
